url: "https://shyamsastha.github.io"

# Use the Minimal theme
remote_theme: pages-themes/minimal

# Enable necessary plugins
plugins:
  - jekyll-remote-theme # Required for using remote themes
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions

# Customize Minimal theme (optional)
minimal:
  skin: dark  # This setting does not exist by default; dark mode needs CSS customization

# Set default layout
defaults:
  - scope:
      path: ""
    values:
      layout: default

github_username: shyamsastha
permalink: /blog/:year/:month/:title.html

# Name shown in nav (optional)
nav_name: "Shyama Sastha Krishnamoorthy Srinivasan"

favicon: /assets/images/favicon.png

title: Shyama Sastha Krishnamoorthy Srinivasan

# Profile image
logo: "/assets/images/profile/1000027231.jpg"

# Short role / title
position: "PhD Candidate, CSE"

# Affiliation / institution
affiliation: "IIIT-Delhi"

# One-sentence tagline / summary (supports Markdown)
description: >
  Researching HCAI and ubiquitous sensing for collective care

# Social & academic links
github: "https://github.com/shyamsastha"
linkedin: "https://www.linkedin.com/in/shyamsastha/"
twitter: "https://x.com/SasthaShyama"
email: "mailto:shyamas@iiitd.ac.in"
orcid: "https://orcid.org/0000-0001-5787-4858"
google_scholar: "https://scholar.google.com/citations?user=8eSnUXoAAAAJ&hl=en"
